**********************************************************************
File "simulem.py", line 1107, in __main__.Simul.layout
Failed example:
    S.load('where2.ini')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.Simul.layout[2]>", line 1, in <module>
        S.load('where2.ini')
      File "/private/staff/n/en/buguen/Documents/rch/devel/repo/pylayers/pylayers/simul/simulem.py", line 1089, in load
        self.wav = wvf()
    TypeError: 'module' object is not callable
**********************************************************************
File "simulem.py", line 1287, in __main__.Simul.pltcir
Failed example:
    S.load('where2.ini')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.Simul.pltcir[1]>", line 1, in <module>
        S.load('where2.ini')
      File "simulem.py", line 1089, in load
        self.wav = wvf()
    TypeError: 'module' object is not callable
**********************************************************************
File "simulem.py", line 1288, in __main__.Simul.pltcir
Failed example:
    S.run2(1,[1])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.Simul.pltcir[2]>", line 1, in <module>
        S.run2(1,[1])
      File "simulem.py", line 2279, in run2
        self.CIR([itx],[irx],store_level=16+8+4+2+1,alpha=alpha)
      File "simulem.py", line 2392, in CIR
        VCl       = Channel.VectChannel(self,l,k,False)
    NameError: global name 'Channel' is not defined
**********************************************************************
File "simulem.py", line 1289, in __main__.Simul.pltcir
Failed example:
    S.pltcir(1,1,mode='linear',noise=False,color='k')
Expected nothing
Got:
    Warning : no furniture file loaded
**********************************************************************
File "simulem.py", line 2147, in __main__.Simul.run2
Failed example:
    S.load('where2.ini')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.Simul.run2[4]>", line 1, in <module>
        S.load('where2.ini')
      File "/private/staff/n/en/buguen/Documents/rch/devel/repo/pylayers/pylayers/simul/simulem.py", line 1089, in load
        self.wav = wvf()
    TypeError: 'module' object is not callable
**********************************************************************
File "simulem.py", line 2148, in __main__.Simul.run2
Failed example:
    out = S.run2(itx,srx)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.Simul.run2[5]>", line 1, in <module>
        out = S.run2(itx,srx)
      File "/private/staff/n/en/buguen/Documents/rch/devel/repo/pylayers/pylayers/simul/simulem.py", line 2279, in run2
        self.CIR([itx],[irx],store_level=16+8+4+2+1,alpha=alpha)
      File "/private/staff/n/en/buguen/Documents/rch/devel/repo/pylayers/pylayers/simul/simulem.py", line 2392, in CIR
        VCl       = Channel.VectChannel(self,l,k,False)
    NameError: global name 'Channel' is not defined
**********************************************************************
File "simulem.py", line 1162, in __main__.Simul.show
Failed example:
    S.load('where2.ini')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.Simul.show[3]>", line 1, in <module>
        S.load('where2.ini')
      File "/private/staff/n/en/buguen/Documents/rch/devel/repo/pylayers/pylayers/simul/simulem.py", line 1089, in load
        self.wav = wvf()
    TypeError: 'module' object is not callable
**********************************************************************
4 items had failures:
   1 of   4 in __main__.Simul.layout
   3 of   4 in __main__.Simul.pltcir
   2 of   6 in __main__.Simul.run2
   1 of   7 in __main__.Simul.show
***Test Failed*** 7 failures.
